apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: rabbitmq
  project: giri-may
spec:
  artifact:
    artifact:
      catalog: default-bitnami
      chartName: rabbitmq
      chartVersion: 14.3.1
    type: Helm
  namespace: cert-manager
  sharing: {}
  version: rabbitmq-v1
