apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  labels:
    team: finance
  name: web-server
  project: giri-may
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/web-server/nginx-15.4.2.tgz
      valuesPaths:
      - name: file://artifacts/web-server/values.yaml
    type: Helm
  namespace: finance
  sharing:
    enabled: true
    projects:
    - name: giri-apr
  version: version2
