apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: cilium-app
  project: giri-may
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/cilium-app/cilium-app.yaml
    type: Yaml
  namespace: finance
  placement:
    selector: rafay.dev/clusterName=giri-aug7-qc,rafay.dev/kubernetesProvider=AKS
  version: cilium-app-v2-202408071417260000
