apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: helm3-chart-upload-multi-v2
  project: giri-may
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx/nginx-9.7.8.tgz
      valuesPaths:
      - name: file://artifacts/nginx/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: new-ns1
  placement:
    selector: rafay.dev/clusterName=giri-aks2-jun4
  version: helm3-chart-upload-multi-v2-v3
