apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: sample-app
  project: giri-may
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/sample-app/sample-app.yaml
    type: Yaml
  namespace: finance
  placement:
    selector: rafay.dev/clusterName=giri-aug7-qc
