apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test-app1
  project: giri-may
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/test-app1/nginx-15.4.2.tgz
      valuesPaths:
      - name: file://artifacts/test-app1/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: finance
  placement:
    selector: rafay.dev/clusterName=giri-aug7-qc
  version: test-app1-v1-202408071434420000
