apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: jul7
  project: giri-may
spec:
  base:
    name: default-aks
    version: 2.9.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  networkPolicy:
    profile:
      name: default
      version: latest
  type: custom
  version: v1
