apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  name: giri-july9
  project: giri-may
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  resourceQuotas: {}
